language: java
sudo: false
install: true
addons: 
  sonarqube:
    organization: "heffebaycay-github"
    token:
      secure: "iSxgpp3E237865UrM8t/nrI367PmAIL/Ibeh43RLYZ844hXXfDZAgr9XeUE7H0Uaa6l4YguZ+d9ZzJudbTJHO7Bd0ce6RfaGgYXWiynR6JmLaUifjlrsrJQ0Of6fhxYSQrRqn3PGvyZZyv0Nwf1nbvkELfa25YUl3jzD+5CYKDTq/ff4OjMLmN/zMOYa0/EaMZon8skcwVyMvwdo/6tWoW1Rv0dzw8cfVzjwY5K9viQdJnmlfSoj8mh1ngcnxqFrTdEMj4KQ5YI9DYSlx4iHwEcKX++IPW5knC2KzftC8SU0ulSwCtdqnGis9jG1vjXLQyA0cT9YRWohJMpzySdjaSyfiIStiCO83ldhRh8vPBlwBFiqRoyzoU3iaRNKyG1vvxnzE2JpDPSLaThkcyPTBefU43VeoOXZoflNImgv2zZBv7F03paiWhZkAD/iC8ifC5H+AeKHGBh4/bYc42hZ0rG7aabjKQs4WhLwG7BKhxQ6eMSigG84Xa9PMHKyUTY8ClPFXELy5OfnF6IyqXjaAtejAIxyq+3Ro3nA/v5sdsK81roKTrdI0ubmkzVh4SS2qIUrDEO+Hdb5cgcAlmeO2ondpUAwzvFsVW8aQkMgUP5miINBiD1pzNt+9wlUup5n3ReCkVugIjTbmNeFTxN7m+iiBR4xFZeNmts4g7+fZPU="
    github_token:
      secure: "Rhxy+MxyqpWjIO5tU+I+WGCStZ25eYo6V9PRCokK5NjzLtAySlswD7gnBYAGz4AqFTOFW0clj8ZyoKFw8Th8q5h6Yjz2RXFOLYtjulnTq6nMVRMUBQ1ruwjDFDp/6vzepBU28pdXks/5X3OYAH0RhZOxyURGg2deBu39Z2ZPjn+ebzv2GvToUWCS7IaSpZHgb19OAXxA3ZSOUJsRrfeN21CbPCuCXae3eIRkp8lrzCs6/NQpzBiiOw6WSBGFgMFseTd7H83uU3B+r2s4omkIOa8Nqly9Tx3MCQ8zBcMytVg52UVR/q5CM9T66DWVFTsC+Rn0moUTOnpxJaUk70fi6JMF2H67c/uYPYDx2sXIOkPtoNLzYbm8Yk4FZJcPyOX32+tAdjhdCs7d1AxMq0X8nLWVtqEI92YjXRUpm/lyHf79MMVm8APH3nbTa2cRQbpYLp3YIto6kcg+6tuFVc1MRTe/p9SwEOoId4JVXPxwYfK2sYv+ngy5Xon6EqgNI9T2yP/8TIMyd21Z7R1uwQ7nIN22NuWVRcP1dB3H8sn8kLEMF1qEMsBWJRuvj3/wB17942u7DyRJd+YaiGP5YVQO4ecOPiNaMGgJGG7092DSN5EXJtFztHaw78PGGLGdmZsY00utdCHpXp6+kZlgNhHYrrXf3zb/iEFJnf8prsXOLpo="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
