language: java
sudo: false
install: true
addons: 
  sonarqube:
    organization: "heffebaycay-github"
    token:
      secure: "mPFviFzNMF7ITxRCGwxNTsTV4XYrQHM1ccPRFHKhx7KtMrkWMgEPD+vZ9iiP3AzLQ3MeRXLimZkLKZT3gk/fztOl4a6+QagsSJe5uPZTzLbkqu36H52p7RW3C7K+V32+ieLo95BKGoynG36ap773j1M0zhmsqb9BuxmZ8oD/trwG9DWJkoQl5sO7rxcyK2ieDtPI4f9I0oATjIGvR6hAM1kKm+iSA5QzGiC0pjCryh+2yJ3MZxgzduehj67rsy4MUBTDzmCumXuUBCgWPI5TvHmW9pRuWScc+mzsGFMfqXUNwk3qlWxAc2j4A9aRek1r3EnxySncrxHDizIgNB2uRIUDDCWGdK0nqCqhACATtOIbdoULwOag/0u2xWJsIZYYZo6PXLkt0ELL8NNK3OZU0a1eq/R6CqFW9+e322apeyzbi7lnSsM1w3tmjl2e3QqLJ4xjj85tgCnN/0HWLfhI3ufXMIubUlxgxAJ/YqHZp46eDyDO5Ucbg8bjnkoQfG5VRZUPbl5vbPTp+jVNmsGhj6UEnRCKj6dl5oDx7fi44c9UymWV8HrSHiaegD24wjTGD0XHUr4OXxozKY9TiWiEpI6GOtvB6AP3gIL9a70keKSgnAASTnoQH/AttgiuCGJNU3Ln6PVgV6EdIGjE72TpM0LUE3q04BhAlfihNnGYw34="
    github_token:
      secure: "ggMhWJ/+wk1aXpb07WDLBd6BEyQsBO0K1r8Y7Pn4UDTDK4MQr+QHXPDfSUar6gR8v8R4Onv37+o2ltR0CtiMbFVr0tQ0rXKUdcXYhw0NFg9QolvJEp4xs2wKzSTLAvJ6HjWjocCe+In8FfSTikHDaNkl2fnM71pElrAMHplccUvkBs3vjKR821salYqLykxrDTnTTwmbSoHebhc+AVXwLGyyrpVXO8w96/+K98ee+0SC/5j2Tklk+LN7SNRi+5tdTv7YtUnvrcTT+VdCEriGriFIAfLSNt2Vmo7YIxomrZd02JKUcwHpxghJtilnSiX81ywfTntP47RJMMWNi6puUO+lQQS25gGodhYlsnLP3KMiosXbYZL5NUn8Lwk2OWUUpLBh1XKHc8mOMiiM87MQRVCmLCIHlNcQ9ARDV+b0VZtegx4fljZqeWRO45mojHRcjHfY5AeXt3JAXbNMmRm2Kpx2hhO8Byna3C0/TXdDEwVQFr8IHY05JTGStHxtOnPNKNPBm4YQbVDBBbIjThlVsZmqjxZr7wOlD4fsJ+uuwIYJCLuULm2JZhe/RnnldR09nGIXqoxU+6mNgqV2L8CrqPK09PndrlbcoiVgKkv1VKteVAJOr0XMl0j455S3UNrTM6Cj0LlXL7vU652IDldUBfcWXd9CPbGTMOR5A+xvTis="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
